[general]
ip = "0.0.0.0"
port = 1239

[database]
wipe = true # Wipe database and create new schema
type = 1     # 0 - sqlite, 1 - PostgreSql 
sqlite_filename = "login.db"

# For PostgreSql
user = "postgres" 
password = "toor"
database = "archeage"
ip = "127.0.0.1"
port = 5432