[general]
ip = "0.0.0.0"
port = 1237
autologin = false

[gamelistener]
ip = "127.0.0.1"
port = 1238
secret = "toor"

[database]
wipe = false # Wipe database and create new schema
type = 1     # 0 - sqlite, 1 - PostgreSql 
sqlite_filename = "login.db"

# For PostgreSql
user = "postgres" 
password = "toor"
database = "archeage"
ip = "127.0.0.1"
port = 5432

# Servers will appear as they declared here 
[servers]
    [servers.1]
    id = 0
    name = "First Server" 
    ip = "92.255.199.47"
    port = 1239
    is_online = true
    is_hidden = false
    type     = 1   # 01- FRESH, 02-UNITED, 03-UNITED
	color   = 0    # 00-BLUE, 01-GREEN, 02-VIOLET, 08-RED
	load     = 1   # 0 - low, 1 - avg, 2 - high

    # [servers.2]
    # id = 1
    # name = "Second Server" 
    # ip = "127.0.0.1"
    # port = 1240
    # is_online = true
    # is_hidden = false
    # type     = 3
    # color   = 2
    # load     = 0   # 0 - low, 1 - avg, 2 - high
